#
#   Copyright 2026 MrDeath404
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

from pathlib import Path
import sys
import os
import stat
import shutil
import subprocess

blob_path = sys.argv[1]

target_file = "Android.mk"
template_file = None
path_variable = "LOCAL_PATH"

simlink_list = []
etc_list = []
etc_xml_list = []
dex_list = []
app_list = []
binary_list = []
library_shared_list = []

def find_and_copy_file(file_name):
    matches = list(Path(blob_path).rglob(file_name))
    for match in matches: 
        if not match:
            print(f"[MISSING] - {file_name}")
            return
        else:
            print(f"[EXISTS] - {file_name}")

        move_path = str(match)
        for source, target in simlink_list:
            move_path = move_path.replace(source, target)
        move_path = "proprietary/" + move_path.removeprefix(f"{blob_path}/")
        move_dir_path = str(Path(move_path).parent)
        
        if not os.path.exists(move_dir_path):
            os.makedirs(move_dir_path)

        shutil.copy2(match, move_path)

def get_abi(filepath):
    result = subprocess.run(
        ['readelf', '-h', filepath],
        capture_output=True, text=True
    )
    for line in result.stdout.splitlines():
        if 'Class:' in line:
            if 'ELF64' in line:
                return '64'
            elif 'ELF32' in line:
                return '32'
    return None

def get_shared_libs(filepath):
    result = subprocess.run(
        ['readelf', '-d', filepath],
        capture_output=True, text=True
    )
    libs = []
    for line in result.stdout.splitlines():
        if '(NEEDED)' in line:
            lib = line.split('[')[-1].rstrip(']')
            libs.append(lib)
    return libs

with open("proprietary-list.txt", "r") as file:
    for line in file:
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        match line.split(":", 1)[0]:
            case "target-file":
                target_file = line.split(":", 1)[1]
            case "template-file":
                template_file = line.split(":", 1)[1]
            case "path-variable":
                path_variable = line.split(":", 1)[1]
            case "simlink":
                simlink_list.append([line.split(":", 1)[1].split(">", 1)[0], line.split(">", 1)[1]])
            case "etc":
                etc_list.append(line.split(":", 1)[1])
            case "etc_xml":
                etc_xml_list.append(line.split(":", 1)[1])
            case "dex":
                dex_list.append(line.split(":", 1)[1])
            case "app":
                app_list.append(line.split(":", 1)[1])
            case "binary":
                binary_list.append(line.split(":", 1)[1])
            case "library-shared":
                library_shared_list.append(line.split(":", 1)[1])

with open("Android.bp", "w") as file:
    file.write("// This file where auto-generated by MrDeath404's extract script\n")
    file.write("\nsoong_namespace {\n}\n")

with open(target_file, "w") as file:
    file.write("// This file where auto-generated by MrDeath404's extract script\n\n")

    if template_file is not None:
        with open(template_file, "r") as template:
            variable_found = False

            for line in template:
                if line.find(f"{path_variable} := ") != -1:
                    variable_found = True
                    break
            template.seek(0)
            
            if not variable_found:
                file.write("LOCAL_PATH := $(call my-dir)\n\n")
                file.write("PRODUCT_SOONG_NAMESPACES += \\\n")
                file.write("\t$(LOCAL_PATH)\n\n")
            
            for line in template:
                file.write(line)
    else:
        file.write("LOCAL_PATH := $(call my-dir)\n\n")
        file.write("PRODUCT_SOONG_NAMESPACES += \\\n")
        file.write("\t$(LOCAL_PATH)\n\n")

bp = open("Android.bp", "a")
mk = open(target_file, "a")

if len(etc_list) > 0:
    mk.write("\n\nPRODUCT_PACKAGES += \\\n")

for etc in etc_list:
    find_and_copy_file(etc)
    paths = list(Path("proprietary").rglob(etc))
    sub_dir = str(paths[0]).split("etc/", 1)[1].rsplit("/", 1)[0]
    bp.write("\nprebuilt_etc {\n")
    bp.write(f"\tname: \"{etc}\",\n")
    bp.write(f"\tsrc: \"{paths[0]}\",\n")
    if sub_dir != etc:
        bp.write(f"\tsub_dir: \"{sub_dir}\",\n")
    bp.write("\tfilename_from_src: true,\n")
    bp.write("}\n")

    mk.write(f"\t{etc}")

    if etc != etc_list[len(etc_list)-1]:
        mk.write(" \\\n")

if len(etc_xml_list) > 0:
    mk.write("\n\nPRODUCT_PACKAGES += \\\n")

for etc_xml in etc_xml_list:
    find_and_copy_file(etc_xml)
    paths = list(Path("proprietary").rglob(etc_xml))
    sub_dir = str(paths[0]).split("etc/", 1)[1].rsplit("/", 1)[0]
    bp.write("\nprebuilt_etc_xml {\n")
    bp.write(f"\tname: \"{etc_xml}\",\n")
    bp.write(f"\tsrc: \"{paths[0]}\",\n")
    if sub_dir != etc_xml:
        bp.write(f"\tsub_dir: \"{sub_dir}\",\n")
    bp.write("\tfilename_from_src: true,\n")
    bp.write("}\n")

    mk.write(f"\t{etc_xml}")

    if etc_xml != etc_xml_list[len(etc_xml_list)-1]:
        mk.write(" \\\n")

if len(dex_list) > 0:
    mk.write("\n\nPRODUCT_PACKAGES += \\\n")

for dex in dex_list:
    find_and_copy_file(dex)
    paths = list(Path("proprietary").rglob(dex))
    dex_name = dex.rsplit(".", 1)[0]
    bp.write("\ndex_import {\n")
    bp.write(f"\tname: \"{dex_name}\",\n")
    bp.write(f"\tjars: [\"{paths[0]}\"],\n")
    bp.write("}\n")

    mk.write(f"\t{dex_name}")

    if dex != dex_list[len(dex_list)-1]:
        mk.write(" \\\n")

if len(app_list) > 0:
    mk.write("\n\nPRODUCT_PACKAGES += \\\n")

for app in app_list:
    find_and_copy_file(app)
    paths = list(Path("proprietary").rglob(app))
    app_name = app.rsplit(".", 1)[0]
    bp.write("\nandroid_app_import {\n")
    bp.write(f"\tname: \"{app_name}\",\n")
    bp.write(f"\tapk: \"{paths[0]}\",\n")
    bp.write("\tcertificate: \"platform\",\n")
    bp.write("\tdex_preopt: {\n\t\tenabled: false,\n\t},\n")
    if str(paths[0]).find("priv-app") != -1:
         bp.write("\tprivileged: true,\n")
    bp.write("}\n")

    mk.write(f"\t{app_name}")

    if app != app_list[len(app_list)-1]:
        mk.write(" \\\n")

if len(binary_list) > 0:
    mk.write("\n\nPRODUCT_PACKAGES += \\\n")

for binary in binary_list:
    find_and_copy_file(binary)
    paths = list(Path("proprietary").rglob(binary))
    sub_dir = str(paths[0]).split("bin/", 1)[1].rsplit("/", 1)[0]
    bp.write("\ncc_prebuilt_binary {\n")
    bp.write(f"\tname: \"{binary}\",\n")
    bp.write("\tstrip: {\n\t\tnone: true,\n\t},\n")
    bp.write("\ttarget: {\n")
    abi = []
    for path in paths:
        if get_abi(path) == "64":
            abi.append("64")
        else:
            abi.append("32")
        arch = "arm64" if abi[len(abi)-1] == "64" else "arm"
        bp.write(f"\t\tandroid_{arch}: {{\n")
        bp.write(f"\t\t\tsrcs: [\"{path}\"],\n")
        bp.write("\t\t\tshared_libs: [\n")
        for lib in get_shared_libs(path):
            bp.write(f"\t\t\t\t\"{lib}\",\n")
        bp.write("\t\t\t],\n")
        bp.write("\t\t},\n")
    bp.write("\t},\n")
    bp.write(f"\tcompile_multilib: \"{"both" if len(abi) == 2 else abi[0]}\",\n")
    bp.write("\tcheck_elf_files: false,\n")
    bp.write("\tprefer: true,\n")
    if sub_dir != binary:
        bp.write(f"\trelative_install_path: \"{sub_dir}\",\n")
    bp.write("\tsoc_specific: true,\n")
    bp.write("}\n")

    mk.write(f"\t{binary}")

    if binary != binary_list[len(binary_list)-1]:
        mk.write(" \\\n")

if len(library_shared_list) > 0:
    mk.write("\n\nPRODUCT_PACKAGES += \\\n")

for library_shared in library_shared_list:
    find_and_copy_file(library_shared)
    paths = list(Path("proprietary").rglob(library_shared))
    lib_name = library_shared.rsplit(".", 1)[0]
    bp.write("\ncc_prebuilt_binary {\n")
    bp.write(f"\tname: \"{lib_name}\",\n")
    bp.write("\tstrip: {\n\t\tnone: true,\n\t},\n")
    bp.write("\ttarget: {\n")
    abi = []
    for path in paths:
        if get_abi(path) == "64":
            abi.append("64")
        else:
            abi.append("")
        arch = "arm64" if abi[len(abi)-1] == "64" else "arm"
        bp.write(f"\t\tandroid_{arch}: {{\n")
        bp.write(f"\t\t\tsrcs: [\"{path}\"],\n")
        bp.write("\t\t\tshared_libs: [\n")
        for lib in get_shared_libs(path):
            bp.write(f"\t\t\t\t\"{lib}\",\n")
        bp.write("\t\t\t],\n")
        bp.write("\t\t},\n")
    bp.write("\t},\n")
    bp.write(f"\tcompile_multilib: \"{"both" if len(abi) == 2 else abi[0]}\",\n")
    bp.write("\tcheck_elf_files: false,\n")
    bp.write("\tprefer: true,\n")
    sub_dir = str(paths[0]).split(f"lib{abi[0]}/", 1)[1].rsplit("/", 1)[0]
    if sub_dir != library_shared:
        bp.write(f"\trelative_install_path: \"{sub_dir}\",\n")
    bp.write("\tsoc_specific: true,\n")
    bp.write("}\n")

    mk.write(f"\t{lib_name}")

    if library_shared != library_shared_list[len(library_shared_list)-1]:
        mk.write(" \\\n")